import "beercss";
import "material-dynamic-colors";

import type { Metadata } from "next";

import { AppBarPC } from "./components/AppBar/AppBar";
import { NavRailPC } from "./components/NavRail/NavRail";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="background">
        <AppBarPC />
        <NavRailPC />
        <main className="small-margin">
          {children}
        </main>
      </body>
    </html>
  );
}
