// Generated by https://quicktype.io

export interface SZ_User {
    name:              string;
    creationTime:      Date;
    lastLoginTime:     Date;
    version:           number;
    rank:              string;
    avatarStyle:       string;
    avatarUrl:         string;
    commentCount:      number;
    uploadedPostCount: number;
    favoritePostCount: number;
    likedPostCount:    number;
    dislikedPostCount: number;
    email:             string;
}
